### ISSUE TITLE
Support for Grakn 1.7.0

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/workbase#271]
## Problem to Solve

Workbase needs to be updated to support Grakn 1.7

## Current Workaround

Use an older version of Grakn

## Proposed Solution

Update Workbase

## Additional Information

Using Windows 10, Workbase 1.2.7, and Grakn 1.7:
![image](https://user-images.githubusercontent.com/3278877/79361642-a0358b00-7f56-11ea-909a-5943dd77e240.png)

```
2020-04-15 20:20:30,084 [main] INFO  grakn.core.server.Grakn - Grakn started in 2.844 s
2020-04-15 20:20:45,564 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
io.grpc.StatusRuntimeException: INVALID_ARGUMENT
	at grakn.core.server.rpc.ResponseBuilder.exception(ResponseBuilder.java:430)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:262)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:188)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by sorsaffari** [comment]
Workbase 1.2.8 supports Grakn core 1.7.0 to 1.7.2
